# Generated by Django 5.1.1 on 2024-12-26 19:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
