# Generated by Django 5.1.1 on 2025-01-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_remove_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
